
linters:
  disable-all: true
  enable:
    - unused

linters-settings: 
  cyclop:
    max-complexity: 15
  gocritic:
    disabled-checks:
      - singleCaseSwitch

issues:
  exclude-rules:
    - path: "."
      linters:
        - typecheck