- id: tfsecurity
  name: TFSecurity
  description: TFSecurity is a tool to statically analyze Terraform templates to spot potential security issues.
  language: golang
  entry: tfsecurity
  pass_filenames: false

- id: tfsecurity-docker
  name: TFSecurity Docker
  description: TFSecurity is a tool to statically analyze Terraform templates to spot potential security issues, uses projects official docker image.
  language: docker_image
  entry: khulnasoft/tfsecurity-alpine
  pass_filenames: false

- id: tfsecurity-system
  name: TFSecurity system
  description: TFsec is a tool to statically analyze Terraform templates to spot potential security issues, uses systems installed tfsecurity.
  language: system
  entry: tfsecurity
  pass_filenames: false
